# Generated by Django 5.1.2 on 2024-11-11 22:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0005_alter_card_card_number_alter_cardholder_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalWallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_type', models.CharField(max_length=50)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('card_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_wallets', to='site_admin.card')),
            ],
            options={
                'db_table': 'digital_wallet',
            },
        ),
        migrations.CreateModel(
            name='WalletSelectionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('cardholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.cardholder')),
            ],
        ),
    ]
