# Generated by Django 5.1.2 on 2024-11-17 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0006_digitalwallet_walletselectiontoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalwallet',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='digitalwallet',
            name='issued_date',
        ),
        migrations.RemoveField(
            model_name='digitalwallet',
            name='wallet_type',
        ),
        migrations.AddField(
            model_name='digitalwallet',
            name='apple_wallet_issued',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='digitalwallet',
            name='apple_wallet_issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalwallet',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digital_wallets', to='site_admin.card'),
        ),
        migrations.AddField(
            model_name='digitalwallet',
            name='google_wallet_issued',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='digitalwallet',
            name='google_wallet_issued_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
