# Generated by Django 5.1.2 on 2024-11-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0007_remove_digitalwallet_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='issued_date',
            field=models.DateField(null=True),
        ),
    ]
