# Generated by Django 5.1.2 on 2024-11-17 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0008_alter_card_card_number_alter_card_issued_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_admin.cardtype'),
        ),
        migrations.AlterField(
            model_name='cardholder',
            name='card_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_admin.cardtype'),
        ),
        migrations.AlterField(
            model_name='cardholder',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_admin.company'),
        ),
        migrations.AlterField(
            model_name='cardholder',
            name='issued_date',
            field=models.DateField(null=True),
        ),
    ]
