# Generated by Django 5.1.2 on 2024-11-17 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0009_alter_card_card_type_alter_cardholder_card_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardholder',
            old_name='issued_date',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='cardholder',
            name='card_type',
        ),
        migrations.AddField(
            model_name='cardholder',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cardholder', to='site_admin.card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='site_admin.cardholder'),
        ),
    ]
