# Generated by Django 5.1.2 on 2024-11-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0011_remove_card_card_type_cardholder_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardholder',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
