# Generated by Django 5.1.2 on 2024-11-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0012_alter_cardholder_created_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_type_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cardholder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='store_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='business_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='check_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tip_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cardholder',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='check_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='store',
        ),
    ]
