# Generated by Django 5.1.2 on 2024-11-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0013_alter_transaction_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='card_type_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cardholder_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='check_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='store_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
